Torgen/codex-blackboard

- lib/model.coffee
- server/bootstrap.coffee
- server/drive.coffee
- server/hubot.coffee
- server/mailwatch.coffee
- server/twitterwatch.coffee
Also allows setting all json settings through environment variables.
Fixes #3
> Allow turning off all batch processing on the server

- client/000startup/settings.coffee
- client/header.coffee
- header.html
Rather than having them be hard-coded.
Fixes #11
> Set picker credentials in settings json

- blackboard.html
- blackboard.less
- client/000startup/settings.coffee
- client/chat.coffee
- client/header.coffee
- client/main.coffee
- client/puzzle.coffee
- client/round.coffee
- header.html
- puzzle.html
- round.html
> Remove all references to the wiki

- client/header.coffee
This makes it render the same as in chat if it contains a space.
> Use canonical nick to render gravatar in login modal and dropdown

- chat.html
- client/000startup/settings.coffee
- client/chat.coffee
- lib/model.coffee
This should be more efficient than the server-side version because it won't involve a query, plus it works even if someone in the room gets a DM.
> Use MutationObserver to compute followups client-side

- blackboard.html
- blackboard.less
Moves round names into status grid.
Fixes #17
> Remove nav panel

- lib/model.coffee
- server/hubot-scripts/codex.coffee
Bot only replies if the callin is in none of these, since the
announcement of the callin is feedback enough.
> Announce callins in general, puzzle, and round chats.

- blackboard.html
- blackboard.less
- chat.html
- client/blackboard.coffee
- client/chat.coffee
- client/puzzle.coffee
- lib/model.coffee
- puzzle.html
- round.html
- server/hubot-scripts/codex.coffee
Activated using the "bot stuck" command, a button next to the call in button, or by editing the stuck tag directly (which takes the place of the status column).
> Stuck status that alerts general chat and lights up on status grid

- client/header.coffee
- header.html
- header.less
Remember where we were when we go up so we can get back there.
> Breadcrumb trail

- blackboard.html
- blackboard.less
- client/blackboard.coffee
- client/main.coffee
- client/mechanics.coffee
- lib/imports/mechanics.coffee
- lib/methods/addMechanic.test.coffee
- lib/methods/favoriteMechanic.test.coffee
- lib/methods/newPuzzle.test.coffee
- lib/methods/removeMechanic.test.coffee
- lib/methods/unfavoriteMechanic.test.coffee
- lib/model.coffee
- mechanics.html
- mechanics.less
- public/sw.js
- puzzle.html
- server/bootstrap.coffee
- server/server.coffee
Puzzles have a 'mechanics' field which is a list of canonical mechanic names. Users have a 'favorite_mechanics' field they can edit with a dropdown on the main blackboard. Puzzles with any mechanic matching a user's favorites are added to their "Favorite Puzzles" section. Adds a notification stream for favorite mechanics; when enabled and a favorite mechanic is added to a puzzle, a notification is fired. Clicking on the notification takes you to the puzzle.
Fixes #92 and lays the groundwork for #107.
> Puzzle mechanics

- blackboard.html
- blackboard.less
- client/blackboard.coffee
- client/main.coffee
Don't say a meta is empty when all the puzzles in it are hidden. Do add a footer saying how many are hidden. Fixes #99
> Hidden puzzles exist

- chat.html
- chat.less
- client/chat.coffee
- lib/model.coffee
- server/server.coffee
They're not actually deleted, just not rendered, so that the last read marker isn't messed up.
Fixes #123
> Allow 'deleting' messages

- server/hubot-scripts/brain.coffee
- server/hubot.coffee
- server/imports/hubot.coffee
Add hubot script that loads data from the DB into the brain, saves it back to the DB periodically, and keeps the users map up to date so other scripts can query it.
> Hubot brain

- .gitignore
- .meteor/packages
- .meteor/versions
- .travis.yml
- README.md
- package-lock.json
- package.json
Can also generate them with coverage (html) or coverage.lcov (lcov) npm scripts.
> Add coverage to travis run

- .meteor/packages
- .meteor/versions
- server/hubot-scripts/brain.coffee
- server/hubot-scripts/brain.test.coffee
- server/hubot-scripts/codex.coffee
- server/hubot-scripts/codex.test.coffee
- server/hubot-scripts/memes.test.coffee
- server/hubot-scripts/metas.coffee
- server/hubot-scripts/metas.test.coffee
- server/imports/botutil.coffee
- server/imports/hubot.coffee
- server/imports/hubot.test.coffee
- server/imports/testutils.coffee
Adds test for the hubot adapter and most of the custom scripts, covering two items for #115.
> Hubot tests

- callins.html
- callins.less
- client/callins.coffee
- client/puzzle.coffee
- lib/imports/callin_types.coffee
- lib/imports/match.coffee
- lib/methods/correctCallIn.test.coffee
- lib/methods/incorrectCallIn.test.coffee
- lib/methods/newCallIn.test.coffee
- lib/model.coffee
- puzzle.html
- server/hubot-scripts/codex.coffee
- server/hubot-scripts/codex.test.coffee
FIxes #110 
Add special callin types for interaction requests, other reasons for contacting HQ, and expected callback (e.g. for after we've submitted a creative exercise).
> Callin types

- client/chat.coffee
More pages have chat now, which means it's possible to go directly from a page with chat to another. This means we need to join the new room when the room_name changes, not in a `messages.onCreated` callback, since the callback won't be called again if the chat room changes to another.
Fixes #156
> Keepalive in chat autorun, not onCreated

- client/callins.coffee
Non-answer callins still play sounds on callins page.
Fixes #159
> Only play sounds for new answer callins unless on callins page

- chat.html
- client/chat.coffee
- splitter.less
Adds a button to hover over a table of the avatar, real/nickname, and relative location of everyone in the room.
Fixes #157
> Show who's in a room in split mode

- blackboard.html
- client/blackboard.coffee
- client/header.coffee
- client/options_dropdown.coffee
- header.html
- header.less
- options_dropdown.html
> Move display options to dropdown

- server/drive.coffee
- server/imports/drive.coffee
- server/imports/drive.test.coffee
> Update Google Drive API to v3

- server/hubot-scripts/codex.coffee
- server/hubot-scripts/codex.test.coffee
> Allow specifying url when creating puzzle or round with bot command

- private/install.sh
- private/installtemplates/etc/codex-common.env.handlebars
Most of #186, except for some wiki changes.
> Update install script to ubuntu 20.04

- client/chat.coffee
Makes it easier to fix wrong bot messages. See cjb#95
> Allow using up and down arrow to fill text box with old messages

- blackboard.html
- blackboard.less
- client/blackboard.coffee
> Add a search box that filters puzzles by presence of a user.

- blackboard.html
- client/blackboard.coffee
- lib/methods/setAnswer.test.coffee
- lib/methods/summon.test.coffee
- lib/model.coffee
- server/imports/hubot.coffee
- server/imports/presence.coffee
- server/imports/presence.test.coffee
- server/server.coffee
Accumulate total time spent in a puzzle room by all solvers until the puzzle is solved. This is the "fun stat" from cjb#80, but it's not graphed.
> Solver minutes

- blackboard.html
- blackboard.less
- callins.html
- callins.less
- chat.html
- client/chat.coffee
- client/main.coffee
- client/puzzle.coffee
- page.html
- puzzle.html
- splitter.less
Pin icon in overlay in corner of meeting keeps you in the same meeting if you change pages. Required a lot of restructuring of the site so the embedded chat wasn't torn down when going between puzzles and the blackboard.
> Allow pinning Jitsi meetings

- callins.html
- client/callins.coffee
- lib/model.coffee
- server/methods/cancelCallIn.test.coffee
- server/methods/correctCallIn.test.coffee
- server/methods/deletePuzzle.test.coffee
- server/methods/favorite.test.coffee
- server/methods/incorrectCallIn.test.coffee
- server/methods/newCallIn.test.coffee
- server/methods/newPuzzle.test.coffee
- server/methods/newRound.test.coffee
- server/methods/renamePuzzle.test.coffee
- server/methods/setAnswer.test.coffee
- server/methods/unfavorite.test.coffee
- server/server.coffee
Removes all reference to the incorrectAnswers field. Also fixes marking already tried answers.
Fixes #209
> Fix marking of already-tried answers

- chat.html
- client/chat.coffee
- splitter.less
It's still tall enough to see the control buttons.
> Allow capping jitsi meeting height at 50px

- blackboard.less
- puzzle.html
> UI tweaks in puzzle info panel

- server/accounts.coffee
> If the password changes, log everyone out

- client/main.coffee
Formerly, the subscription was to all oplogs since the session started. This is a fast initial query, since it's indexed and there won't be oplogs in the future, but the messages would accumulate int he client. Whenever an oplog arrives, set the cutoff for future oplogs to the timestamp of that message, with debounce so we don't update the subscription super often. The resubscriptions are also fast, but allow the server and the client to unload the already notified on oplog messages.
> Let oplogs age out

- header.html
- header.less
> Limit puzzle name in breadcrumbs to 20em

- callins.html
- callins.less
- client/callins.coffee
- client/main.coffee
- puzzle.html
> Add copy and go button to callins table on puzzles

- blackboard.html
- client/blackboard.coffee
> Correct logic for hiding rounds when all metas/unassigned are solved

- lib/imports/duplicate.coffee
- lib/model.coffee
- server/hubot-scripts/codex.coffee
- server/hubot-scripts/codex.test.coffee
- server/methods/newPuzzle.test.coffee
- server/methods/newRound.test.coffee
> Return error instead of creating new object with duplicate name

- client/blackboard.coffee
- client/chat.coffee
- client/header.coffee
- client/puzzle.coffee
- lib/model.coffee
- server/server.coffee
> Remove canonical from model

- client/splitter.coffee
> Limit chat height to window height minus header

- chat.html
- client/chat.coffee
> Link back to room of pinned Jitsi meeting

- client/header.coffee
- header.html
- lib/model.coffee
- server/server.coffee
> Show private messages from all rooms in recent header chats

- client/blackboard.coffee
Also fixes clearing the search.
Fixes #314
> Adds typeahead to filter by user presence

- client/blackboard.coffee
- client/main.coffee
> Support notification on private message

- blackboard.html
- blackboard.less
- client/blackboard.coffee
Which are collapsed are stored in local storage.
Fixes #254
> Optionally collapse rounds and metas

- blackboard.html
- client/blackboard.coffee
- client/main.coffee
- lib/model.coffee
- server/server.coffee
It disables the ability to drag and drop.
Fixes #261
> Allow ordering puzzles in a meta alphabetically

- blackboard.html
- server/bootstrap.coffee
Also set round link correctly in bootstrap data.
Fixes #364
> Size round links like chat link in headers

- client/puzzle.coffee
Since spreadsheet doesn't render well.
Fixes #366
> Default puzzle view on mobile is info

- blackboard.less
- chat.html
- chat.less
- client/chat.coffee
- client/header.coffee
- client/imports/linkify.coffee
- client/main.coffee
- header.html
- header.less
- lib/model.coffee
- server/server.coffee
Adds a box of all private messages to you to the avatar dropdown. Includes a badge of the number of unread private messages.
Fixes #385, Fixes #386
> Private message drawer

- blackboard.html
- client/blackboard.app-test.coffee
> Fix adding puzzle to existing meta via UI

- chat.html
- chat.less
- client/chat.app-test.coffee
- client/chat.coffee
On /msg at the start or @ anywhere, pop up a typeahead menu of all nicks on the server. It can be navigated by keyboard or mouse.
Fixes #368
> Chat typeahead

- client/imports/textify.coffee
- client/main.coffee
> Convert private messages with HTML bodies to text for desktop notifications

- chat.html
- chat.less
- client/blackboard.coffee
- client/chat.app-test.coffee
- client/chat.coffee
- client/header.coffee
- client/imports/app_test_helpers.coffee
- client/main.coffee
- header.html
- header.less
- lib/model.coffee
- server/hubot-scripts/codex.test.coffee
- server/hubot-scripts/metas.test.coffee
- server/imports/hubot.coffee
- server/imports/hubot.test.coffee
- server/imports/newMessage.coffee
- server/server.coffee
@ plus a nickname adds the nickname to the "mentions" list for the message. Messages with you in the mentions are highlighted, instead of parsing the test for your nickname. Mentions are a tab in the avatar dropdown header like private messages so you can see them when they happen in another room.
> Use @ to mark mentions and track them as first class message fields

- client/main.coffee
Also silence notifications when sound effects are disabled. Fixes #416
> Silence notifications that already have sound

- blackboard.less
- client/imports/jitsi.coffee
> Only fade non-jitsi presence when jitsi is enabled

- client/header.coffee
- client/main.coffee
- client/notification.app-test.coffee
- docs/Oncall.md
- lib/model.coffee
- server/hubot-scripts/codex.coffee
- server/hubot-scripts/codex.test.coffee
- server/methods/setStarred.test.coffee
- server/server.coffee
Only the first time. other rooms aren't affected.
Fixes #398
> Starring a message in main chat announces it

- client/chat.coffee
> Scroll to unread mention/pm when joining chat

- server/imports/drive_change_polling.coffee
> Don't crash when a drive file is deleted

- chat.html
- client/chat.coffee
UI changed and controls were cut off at 50px.
> Change capped jitsi height to 75px

- package-lock.json
- package.json
- server/imports/twitter.coffee
- server/twitterwatch.coffee
> Switch from twit to twitter-api-v2

- client/chat.coffee
Everything's useful if you're not hiding tomfoolery.
Fixes #467
> Correct sense of hide bot tomfoolery

- server/hubot-scripts/codex.test.coffee
If you don't wait for the response, it can be inserted after the database is cleared and be present for the next test case.
> Wait for response in some hubot tests

- blackboard.html
- blackboard.less
- client/blackboard.coffee
- lib/model.coffee
- server/methods/newPuzzle.test.coffee
- server/server.coffee
> Drive fix UI

- client/imports/settings.coffee
freeze is on the Object class, not  on objects.
Fixes #475
> Fix compact mode

- blackboard.html
> Don't apply puzzle filter to edit page

- client/chat.coffee
- lib/imports/canonical.coffee
- lib/imports/canonical.test.coffee
- lib/imports/settings.coffee
- lib/model.coffee
- server/methods/newPuzzle.test.coffee
- server/methods/newRound.test.coffee
It's been hyphen instead of underscore for the past few years.
Cherry-picked heavily from cscott's branch.
> Allow changing URL separator

- server/calendar.coffee
- server/drive.coffee
- server/imports/googlecommon.coffee
> Add 403 to response codes to try on google APIs

- .meteor/packages
- .meteor/versions
- chat.less
- header.less
- options_dropdown.less
- splitter.less
Also remove escapes from calc, since they're no longer required.
> Update less to 4.0.0

- .github/actions/diff-bundle-stats/action.yml
- .github/actions/diff-bundle-stats/dist/index.js
- .github/actions/diff-bundle-stats/package-lock.json
- .github/actions/diff-bundle-stats/package.json
- .github/actions/diff-bundle-stats/src/main.js
- .github/workflows/bundlesize.yml
> Github action to compare bundle, package, and module sizes for pull requests

- client/000startup/settings.coffee
- client/header.coffee
- header.html
- header.less
- page.html
Drive folder is accessible in the hamburger menu.
New app keys have domain restrictions for picker, so it's not useful to us now.
> Remove picker code

- client/chat.coffee
- client/jitsi.app-test.coffee
> Wait until conference is joined before sending commands

- client/imports/puzzle_drag.app-test.coffee
> Extend drag-and-drop timeout even more

- blackboard.html
- blackboard.less
- client/blackboard.app-test.coffee
- client/blackboard.coffee
Also give warnings about error situations.
Fixes #550
> Don't allow clobbering a tag by renaming another

- client/imports/move_within_parent.coffee
- lib/model.coffee
- server/imports/move_within_parent.coffee
- server/methods/locateNick.coffee
- server/methods/locateNick.test.coffee
For methods where they're substantially different, e.g. because the server code uses rawCollection.
> Separate client and server implementations

- lib/model.coffee
It was possible to create a new puzzle in a round at the same time as someone was deleting the round, which would leave the puzzle in the database with no way of seeing it. This prevents that by having the check for the round being empty happen as part of the remove call.
> Fix race condition on deleteRound

- server/hubot-scripts/metas.test.coffee
Always wait for the response.
Fixes #579
> Fix more flaky metas tests

- .meteor/packages
- .meteor/versions
- blackboard.html
- client/blackboard.app-test.coffee
- client/blackboard.coffee
- client/chat.app-test.coffee
- client/chat.coffee
- client/main.coffee
- client/puzzle.coffee
- header.less
- puzzle.html
Instead of opening a modal, appear to create a virtual object with the title focused, and actually create it on the same events that would edit the title.
Fixes #546
> Create things in place

- client/chat.coffee
- lib/model.coffee
- server/imports/newMessage.coffee
- server/methods/newMessage.coffee
They are skipped with up and down in the chat box.
Fixes #619
> Set on_behalf on messages created on your behalf

- server/hubot-scripts/metas.test.coffee
Always wait for the response from the bot instead of just watching for the results.
Fixes #579
> More flaky metas script test fixes

- client/chat.app-test.coffee
- lib/imports/callin_types.coffee
- lib/imports/match.coffee
- lib/model.coffee
- server/setup.app-test.coffee
> Enumerate goodness instead of badness in setField

- package-lock.json
- package.json
> Get hubot from my fork

- blackboard.html
- blackboard.less
- client/blackboard.coffee
- client/imports/ok_cancel_events.coffee
- client/imports/ui/components/tag_table_rows/tag_table_rows.coffee
- client/imports/ui/components/tag_table_rows/tag_table_rows.html
- client/puzzle.coffee
- puzzle.html
> Add tag from puzzle info panel

- blackboard.html
- blackboard.less
- chat.html
- client/geolocation.coffee
- client/gravatar.coffee
- client/imports/ui/components/tag_table_rows/tag_table_rows.html
- client/imports/ui/pages/map/cluster.html
- client/imports/ui/pages/map/map.coffee
- client/imports/ui/pages/map/map.less
- gravatar.html
- gravatar.less
- package-lock.json
- package.json
- server/server.coffee
> Track who's online

- client/splitter.coffee
- splitter.html
- splitter.less
> Cap top right height at content size

- .meteor/packages
- .meteor/versions
- client/callins.coffee
- client/main.coffee
Reduces size of server bundle by ~60M for some reason.
> Use native Clipboard API

- client/imports/ui/pages/logistics/logistics.coffee
> Trim names of dragged links

- .github/workflows/test.yml
Will hopefully mean we get the full coverage instead of just the worst single run.
> Use rerun coverage webhook

- package-lock.json
- package.json
- page.html
- public/fontawesome/css
- public/fontawesome/webfonts
The CDN seems not to be setting the CORS header correctly anymore.
Fixes #763
> Serve fontawesome instead of using CDN

- .github/workflows/bundlesize.yml
- .github/workflows/test.yml
- .gitmodules
- .meteor/packages
- .meteor/versions
- lib/model.js
- server/methods/newPuzzle.test.js
> Use transactions for racy updates

- .github/workflows/test.yml
- .meteor/versions
- client/blackboard.app-test.js
- client/jitsi.app-test.js
- client/login.app-test.js
- package-lock.json
- package.json
Runs them in both chromium and firefox.
> Use playwright for tests

- client/imports/ui/components/splitter/splitter.js
The mousedown and mouseup events were emulated but not mousemove, so added explicit touchstart, touchmove, and touchend handlers. Fixes #773
> Allow resizing splitters on touchscreens

- client/imports/ui/components/splitter/splitter.js
- client/imports/ui/components/splitter/splitter.less
> Make splitter handles bigger on touch screens

- client/imports/ui/components/splitter/splitter.js
Default is 1/4 of screen width, capped at 300px. (You can make it more.) Fixes #775
> Base default splitter width on window width

- client/puzzle.js
Was probably broken during decaffeination
> Fix cares about and meta_ tags

- client/blackboard.html
- client/blackboard.js
- client/blackboard.less
- client/header.html
- client/header.less
Should help with mobile usability (#259)
> Move lock/unlock to bottom on narrow screens

- client/blackboard.html
- client/blackboard.less
- client/imports/ui/components/edit_tag_value/edit_tag_value.html
> Turn blackboard table into cards on very narrow screens

- client/blackboard.app-test.js
- client/blackboard.html
- client/chat.html
- client/header.html
- client/header.js
- client/imports/ui/pages/logistics/logistics.html
- client/link.html
- client/main.js
- client/page.html
- lib/model.js
- server/hubot-scripts/codex.js
- server/methods/newMessage.test.js
Moved it out of header.js since it's not particular to the header. Also made it match on the href starting with a slash instead of on a class.
> Link click handler cleanup

- client/header.html
- client/header.js
- client/imports/ui/components/connection_button/connection_button.html
- client/imports/ui/components/connection_button/connection_button.js
- client/imports/ui/pages/graph/graph_page.js
- client/imports/ui/pages/map/map_page.js
- client/imports/ui/pages/statistics/statistics_page.js
Since it's used on pages that don't have the header.
> Make connection button a component

- private/install.sh
- private/installfiles/etc/mongod.conf
- private/installfiles/etc/systemd/system/codex-batch.service
- private/installfiles/etc/systemd/system/codex@.service
- private/installtemplates/etc/codex-common.env.handlebars
- private/installtemplates/etc/nginx/sites-available/codex.handlebars
> Update install script to use unix sockets

- client/blackboard.app-test.js
- client/blackboard.js
- client/callins.js
- client/chat.app-test.js
- client/chat.html
- client/chat.js
- client/header.html
- client/header.js
- client/header.less
- client/imports/ui/pages/map/map.js
- client/imports/ui/pages/map/summarize_markers.js
- client/imports/ui/pages/map/summarize_markers.test.js
- client/main.js
- client/puzzle.js
- lib/imports/callin_types.js
- lib/model.js
Combination of a few more tests, ignoring some infeasible branches, and some dead code deletion.
> Bump coverage by about 1.5% absolute

- client/imports/ui/pages/projector/projector.app-test.js
- client/imports/ui/pages/statistics/statistics_chart.js
- lib/imports/collections.js
- lib/imports/settings.js
- server/batch.js
- server/imports/periodic_stats.js
- server/imports/periodic_stats.test.js
- server/server.js
Add them to the statistics graph as a second axis.
Fixes #491
> Periodically collect number of solvers online

- client/gravatar.less
> Fix badge opacity

- client/imports/ui/pages/statistics/statistics_chart.js
> Stack presence on top of solved and unlocked lines

- client/imports/ui/pages/statistics/statistics_chart.js
> Correct sorting specification in statistics graph

- client/imports/settings.js
- client/main.js
> Ask for notification permission on first login

- client/blackboard.html
- client/blackboard.js
- client/blackboard.less
- client/chat.less
> Split jitsi and chat presence onto separate lines

- client/imports/ui/pages/statistics/puzzle_feed.js
- client/imports/ui/pages/statistics/statistics_chart.js
> Add provided puzzles to statistics chart

- lib/model.js
> Allow setting link on round

- client/blackboard.app-test.js
- client/blackboard.html
> Don't say there are no puzzles if they're all solved and hidden

- client/chat.html
- client/chat.js
- client/chat.less
If you're not in the jitsi for your room and other people are, show how many of them there are on the join button. Fixes #933
> Indicate presence of jitsi while closed

- client/answer_sound.js
- client/blackboard.js
- client/imports/notification.js
- client/imports/serviceworker.js
- public/sw.js
Uses serviceworker to synchronize between windows. The first window to get the event plays the sound. Fixes #935
> Only play solved noise in one window

- client/geolocation.js
Saves a little space in the chat headers. Fixes #964
> Don't tell you you're near yourself

- client/chat.less
> Fix chat window padding between 480px and 980px

- client/imports/ui/components/edit_tag_value/edit_tag_value.html
> Don't format answers in blackboard

- client/imports/ui/pages/logistics/logistics.app-test.js
- client/imports/ui/pages/logistics/logistics.js
> Use url if dropped html has no text

- client/blackboard.js
- client/imports/presence_index.js
- client/imports/ui/pages/logistics/logistics.js
> Insert 0s on presence index doc creation

- client/blackboard.js
- client/imports/jitsi.js
> Include JWTs in links to jitsi

- client/imports/jitsi.js
> Disable moderator and join/part notifications

- client/imports/ui/pages/statistics/puzzle_feed.js
- client/imports/ui/pages/statistics/puzzle_feed.test.js
- client/imports/ui/pages/statistics/statistics_chart.js
> Style solved metas differently on statistics

- client/puzzle.html
> Nudge to set theme for new puzzles

- client/callins.html
- client/callins.js
- client/callins.less
- client/imports/ui/pages/logistics/logistics.less
- package-lock.json
- package.json
Since this makes the dropdown much taller, I had to add floating-ui to allow it to escape from block formatting contexts.
Fixes #1153
> Add explanations to callin type dropdown

- client/callins.js
- client/chat.js
- client/header.html
- client/header.js
- client/main.js
- client/puzzle.js
- lib/imports/server_settings.js
- server/imports/hubot.js
Helpers that don't get called by their template, etc.
> Cruft cleanup

- .github/workflows/test.yml
- package.json
Make the browser-specific runs run client only, and make a run that doesn't specify browser that runs server only.
> Only run server unit tests once

- lib/model.js
- server/methods/setTag.test.js
> Notify feeders on special tag changes on metas

- client/blackboard.html
- client/blackboard.js
- client/options_dropdown.html
> Don't prioritize stuck feeding solved meta

- client/blackboard.js
- client/chat.app-test.js
- client/chat.html
- client/chat.js
- client/imports/chunk_text.js
- client/imports/chunk_text.test.js
- client/imports/presence_index.js
- client/imports/ui/pages/logistics/logistics.js
- client/imports/ui/pages/logistics/logistics.less
- client/main.js
- client/presence.less
- client/puzzle.html
- client/puzzle.js
- client/text_chunk.html
- client/text_chunk.js
- client/text_chunk.less
- server/hubot-scripts/codex.js
- server/hubot-scripts/codex.test.js
- server/hubot-scripts/metas.js
- server/hubot-scripts/metas.test.js
- server/imports/botutil.js
- server/server.js
Start with a # like an IRC channel, but converted to a live-updating link. e.g. if a mentioned puzzle is renamed or solved, the link will reflect that.
Fixes #1179
> Room mentions

- client/imports/storage.js
It means the entire storage area was cleared.
> Support empty key in storage event

- client/imports/ui/pages/logistics/logistics.app-test.js
- lib/model.js
- server/methods/correctCallIn.test.js
- server/methods/incorrectCallIn.test.js
> Notify on solve

- lib/model.js
- server/methods/newCallIn.test.js
Instead of the current name of the room.
Fixes #1314
> Put room mention on new callins

- client/blackboard.app-test.js
- client/blackboard.html
- client/blackboard.js
- client/blackboard.less
even if solved puzzles are globally hidden.
Fixes #1326
> Allow showing the solved puzzles for a meta

- lib/imports/canonical.js
- lib/imports/canonical.test.js
other than lowercasing.
Fixes #1317
> Leave letters alone in canonicalization

- .github/workflows/bundlesize-comment.yml
- .github/workflows/bundlesize.yml
Build in PR; comment from outside with elevated permissions
Fixes #1383
> Split bundle size diff

- client/chat.html
- client/chat.js
- client/chat.less
Means short messages are less likely to overflow; also makes it less painful to add more controls.
> Put delete and star controls in hover popup

- client/imports/chunk_text.js
- client/imports/chunk_text.test.js
- client/main.js
> Convert room mentions to room name in notifications

- client/chat.js
Fixes flakiness in searching by name
> Only match id in typeahead with room type

- server/imports/hubot.js
- server/imports/hubot.test.js
> Bot doesn't join room to respond privately

- client/blackboard.html
- client/blackboard.js
- client/imports/ui/components/meta_sort_order/index.js
- client/imports/ui/components/meta_sort_order/meta_sort_order.html
- client/imports/ui/pages/logistics/logistics.app-test.js
- client/imports/ui/pages/logistics/logistics.html
- client/imports/ui/pages/logistics/logistics.js
- client/puzzle.app-test.js
- client/puzzle.html
- client/puzzle.js
Use it on the puzzle info panel and obey it both there and in logistics.
Fixes #1403
> Refactor meta sort order control

- lib/model.js
Enforce name, specify link, and don't allow drive, spreadsheet, or doc, as we will always clobber them.
> Accurate param checks for newPuzzle

- client/chat.app-test.js
- client/imports/app_test_helpers.js
- client/imports/ui/mixins/floating_dropdown.js
- client/jitsi.app-test.js
- client/notification.app-test.js
- client/puzzle.app-test.js
- server/batch.js
> Test improvements to hopefully make firefox app tests less flaky

- server/imports/hubot.js
instead of an observer which holds all the messages in memory.
Fixes #1424
> Use change stream for hubot adapter

- client/chat.js
Includes window resizing, frame resizing, and joining the jitsi.
Fixes #1398
> Stay scrolled to bottom when resizing

- client/chat.app-test.js
- client/chat.html
- client/chat.js
- client/chat.less
- client/imports/contenteditable_selection.js
- client/imports/contenteditable_selection.test.js
- client/page.less
Text area expands if your input is larger than will fit.
Fixes #1469
> Expanding text input

- docs/Operations.md
- ops/installtemplates/etc/codex-per-team.env.handlebars
- server/drive.js
- server/imports/drive.js
- server/imports/drive.test.js
- server/imports/drive_change_polling.js
- server/imports/drive_change_polling.test.js
- server/imports/googlecommon.js
> Support shared drives

- client/imports/chunk_text.js
- client/imports/chunk_text.test.js
> Don't interpret @ on its own as a mention
