Torgen/codex-blackboard

chat.html, chat.less, lib/model.coffee
This makes consecutive ones collapse into a single or small number of lines, saving space when there's a mass join or exodus, including after a server restart.
=> Make join/part messages inline-block

server/drive.coffee
We have a 1000 queries per 100 seconds quota, but it seems to be applied as 10 queries per second. When starting multiple copies of the blackboard software at once, they can all try to ensure the drive folder exists and has the right permissions at the same time, which can exhaust this limit. This does an exponential backoff in the hopes that the quota will reset.
Fixes #22
=> Backoff on Drive api when rate limited

blackboard.html, blackboard.less, client/blackboard.coffee, client/chat.coffee, client/main.coffee, lib/model.coffee, server/hubot-scripts/codex.coffee
Oplog messages to which one might want to subscribe are given streams. Each stream can be separately subscribed to or unsubscribed from via an interface on the blackboard main page, which is persistent and reactive between tabs.
=> Enable desktop notifications from Oplog messages

blackboard.less, client/blackboard.coffee, client/header.coffee, client/main.coffee, client/puzzle.coffee, header.html, header.less, puzzle.html
Icons in breadcrumbs behave as tabs, changing what displays in the spreadsheet area of the three-pane view.
Fixes cjb/codex-blackboard#322.
Covers some of what cjb/codex-blackboard#93 and cjb/codex-blackboard#131 were asking for.
=> Puzzle tabs

client/blackboard.coffee, lib/imports/tags.coffee, lib/imports/tags.test.coffee, lib/methods/addIncorrectAnswer.test.coffee, lib/methods/cancelCallIn.test.coffee, lib/methods/correctCallIn.test.coffee, lib/methods/deleteAnswer.test.coffee, lib/methods/deletePuzzle.test.coffee, lib/methods/deleteRound.test.coffee, lib/methods/deleteRoundGroup.test.coffee, lib/methods/incorrectCallIn.test.coffee, lib/methods/newCallIn.test.coffee, lib/methods/newPuzzle.test.coffee, lib/methods/newRound.test.coffee, lib/methods/newRoundGroup.test.coffee, lib/methods/renamePuzzle.test.coffee, lib/methods/renameRound.test.coffee, lib/methods/renameRoundGroup.test.coffee, lib/methods/setAnswer.test.coffee, lib/methods/summon.test.coffee, lib/methods/unsummon.test.coffee, lib/model.coffee, server/batch.coffee
Objects are keyed by canonical form of tag name. This means more than one of them can be set in a single update, they can be set directly instead of requiring a racy read/write loop, they can be looked up in constant time instead of linear scan/binary search, and they can be used as sort keys or query criteria.
To migrate list-style tags to object-style tags, set migrateTags: true in your meteor settings. (This only needs to be done once.)
=> Use embedded object for tags instead of array

blackboard.less, client/puzzle.coffee, puzzle.html
Any tag whose name starts with the word "meta" will display in the puzzle info of all puzzles in that round.
If a meta has a tag named "cares about", whose value contains a comma-separated list of tag names, a column will be added to the table of leaf puzzles in its puzzle info for each such tag name containing that puzzle's value for that tag. If the tag isn't set, a prompt to set it will be added to the leaf puzzle's puzzle info.
=> Propagate tags between meta and leaf puzzles

.meteor/packages, .meteor/versions, blackboard.html, blackboard.less, client/blackboard.coffee, client/imports/objectColor.coffee, client/main.coffee, client/puzzle.coffee, package-lock.json, package.json, page.html, puzzle.html
Also adds color to background of puzzle info frame to help distinguish it from that of its round. Colors are based on hash of round/puzzle id by default, but can be set with color tag, for which a color picker is provided on the blackboard in edit mode.
=> Add color to rounds to help distinguish them

client/main.coffee
This stops you from getting notifications for events that happened after you opened the window, but before you enabled notifications, if you have a window open that isn't normally subscribed to oplogs--for example, a chat window. It doesn't stop you from getting notifications that happened while you were disconnected if you were subscribed before you were disconnected.
=> Suppress notifications until subscription is ready

client/splitter.coffee
This will hopefully prevent the chat window size from becoming lost if it's dragged to full-min size
=> ensure Splitter size remains positive

chat.html, chat.less, client/000startup/settings.coffee, client/chat.coffee, client/header.coffee, client/imports/nickEmail.coffee, client/main.coffee, client/oplog.coffee, lib/methods/correctCallIn.test.coffee, lib/methods/incorrectCallIn.test.coffee, lib/methods/newCallIn.test.coffee, lib/methods/newPoll.test.coffee, lib/methods/setStarred.test.coffee, lib/methods/summon.test.coffee, lib/methods/unsummon.test.coffee, lib/model.coffee, server/batch.coffee, server/server.coffee
There's now a single messages collection with all the messages in it. I'm confident any performance issues that caused in the past are fixed by better indexing, and by being able to apply a limit to the cursor you return from a publish. There's still a button to load history, but it adds it to the current view instead of viewing just the history page. I haven't added continuous scrolling, but this will make it possible.
=> Eliminate fixed paging and OldMessages collection

.travis.yml, package.json, server/bootstrap.coffee, server/drive.coffee
Run parallel builds of the unit tests and a 'full app' test so our coverage report includes all the server-side code. Also tests the bootstrap data loading, as requested in #115.
=> Include all server code in coverage report

client/blackboard.coffee, client/favorite.coffee, lib/methods/favorite.test.coffee, lib/methods/unfavorite.test.coffee, lib/model.coffee, server/server.coffee
Changes the set of users who've favorited a puzzle to a sub-document, so that filtering it to just the current user can be done with the oplog observe driver instead of having to use the polling driver like the $elemMatch version did.
Fixes #138
=> Make puzzles queries use oplog driver

blackboard.less, chat.less, client/main.coffee, client/puzzle.coffee, header.html, page.html, puzzle.html, splitter.less
Allow expanding the splitter view on puzzle pages to fullscreen without the header. Also moves the "open in new tab" link out of the margin, which allowed eliminating the margin and gaining 40px of horizontal and 20px of vertical space.
Fixes #148.
=> Fullscreen

blackboard.less, callins.html, callins.less, client/callins.coffee, client/header.coffee, client/main.coffee, client/puzzle.coffee, lib/imports/callin_types.coffee, lib/methods/addIncorrectAnswer.test.coffee, lib/methods/cancelCallIn.test.coffee, lib/methods/correctCallIn.test.coffee, lib/methods/incorrectCallIn.test.coffee, lib/methods/newCallIn.test.coffee, lib/methods/setAnswer.test.coffee, lib/model.coffee, puzzle.html, server/batch.coffee, server/server.coffee
Adds a status field to callins which starts at "pending" and updates to "accepted", "rejected", or "cancelled" depending on resolution. The callins table only shows the pending callins.
Adds a table to the puzzle info page showing all callins for that puzzle including resolution, and for pending callins, buttons to resolve the callin immediately. 
Fixes #147. Fixes #149.
=> Keep callins

blackboard.html, client/blackboard.coffee
When checked, favorite puzzles (either by mechanic or explicit heart-click) are hidden when solved, regardless of the status of the general "hide solved" button.
Fixes #145
=> Option to hide solved favorites

server/imports/drive.coffee, server/imports/drive.test.coffee
When creating a new puzzle, create the spreadsheet and doc in parallel. Also, start creating the spreadsheet and doc while waiting to set the permissions on the folder.
When setting permissions on an object, set them all in parallel.
When renaming a puzzle, rename the folder, the spreadsheet, and the doc in parallel.
When deleting a directory, delete the contents in parallel.
Also removes apiThrottle, since the modern Google APIs client does this for us.
Did a quick speed test. On 3 puzzle creations in serial, the times were 7775.491ms, 11629.559ms, and 6735.919ms. On 3 creations in parallel, they were 5647.905ms, 4974.740ms, and 3702.866ms. 
Fixes #167
=> Increase parallelism in drive client

blackboard.less, callins.html, client/callins.coffee, client/puzzle.coffee, puzzle.html
Both the callin page and the callin history table in the puzzle info have a dropdown for the callin type where a new type can be selected.
Fixes #161
=> Allow changing type of pending callins

chat.html, client/chat.coffee, client/options_dropdown.coffee, options_dropdown.html
Add options checkbox that hides all joins and parts older than 1h. Doesn't change subscriptions, so they are still sent to the client.
Fixes #169
=> Allow hiding old presence messages

blackboard.html, client/main.coffee
Still shows them when editing, since everything's visible in edit mode.
Also doesn't put the favorite puzzles at the top in edit mode.
Fixes #183
=> Hide empty rounds when hiding solved metas

client/000startup/settings.coffee, client/imports/jitsi.coffee, lib/imports/settings.coffee, lib/imports/settings.test.coffee, private/installtemplates/etc/codex-common.env.handlebars
This means visitors to the site have to be logged in to receive it, unlike when it was a public setting.
=> Store static jitsi room in a global dynamic setting

client/header.coffee, header.html, page.html
If it's already logging in when you load the page, e.g. because you were already logged in, don't show a brief flash of the login dialog. (But do show it if the login fails.)
=> Suppress login dialog if no manual action is needed

server/imports/drive.coffee, server/imports/drive.test.coffee
Need to specify fields in permissions.list for emailAddress to be present.
Parents is a list of strings, not a list of {id: string}.
File discovery isn't allowed to be set when sharing a file with a person.
=> Fix mistakes in Drive v3 migration

chat.html, client/chat.coffee, header.html
It leaves the meeting before opening the new tab
=> Replace video icon in breadcrumbs with pop-out link over video

blackboard.less, chat.html, chat.less, client/blackboard.coffee, client/header.coffee, client/main.coffee, client/options_dropdown.coffee, favorite.less, header.html, header.less, options_dropdown.html, page.html, puzzle.html, splitter.less
Makes the header one line. Moves sound effects mute to the settings menu. Adds a single combined oplog/main chat widget to the end of the breadcrumbs, except on pages that already have main chat where it's oplogs only.
Fixes #223
=> Micro header

blackboard.html, blackboard.less, client/blackboard.coffee
This helps if the stored value is so large that it exceeds the browser's URL limit for the meeting iframe.
Fixes #227
=> Add button that clears Jitsi's local storage

chat.less
Since chats that mention you and private messages are blue, make the read line orange to have better contrast.
Fixes #231
=> Make read line orange

client/header.coffee, lib/model.coffee, server/imports/hubot.coffee, server/imports/newMessage.coffee, server/server.coffee
Causes them to be excluded from the recent chat bar in the header. Primarily used for messages that are sent at the same time as an oplog, since they would be redundant in the header.
=> Add header_ignore field to messages

client/imports/jitsi.coffee, docs/Solving.md
If present, used instead of roomType_roomId to generate the jitsi meeting URL. Useful if certain URLs have problems because of server issues.
fixes #247
=> Override jitsi meeting url with jitsi tag

server/batch.coffee
Any callin created with the 2021 version has a status, so we don't need to set it. Similarly, it doesn't have the target + answer index so we don't need to drop it.
Users won't have their gravatar set with a stored email address, so we don't need to convert it to an md5.
=> Remove compatibility shims

client/splitter.coffee
Windows whose inner height rounds down to the same multiple of 300 pixels share dimensions, so if all your windows are the same height it will work as before, but if you have both portrait and landscape windows they'll be different.
Fixes #309
=> Group splitter dimensions by window height

blackboard.html, callins.html, client/header.coffee, client/link.coffee, header.html, link.html, oplog.html, puzzle.html
This saves a bunch of HTML parsing since Blaze would otherwise have to parse the HTML of the link into DOM objects instead of generating it as DOM objects to begin with.
Fixes #358
=> Make links a template instead of a helper

blackboard.html, blackboard.less, client/blackboard.app-test.coffee, client/blackboard.coffee, client/imports/app_test_helpers.coffee, lib/model.coffee, server/server.coffee, server/setup.app-test.coffee
Adds a publish that inserts a last_message_timestamp and last_read_timestamp into the Puzzle object, and subscribes to it for favorite puzzles. It's shown in the "status" column for favorite puzzles.
Fixes #369
=> Track last chat message against last read in favorite puzzle

blackboard.less, client/puzzle.coffee, puzzle.html
Uses form-horizontal and control groups to better separate callin type from source and so surprise wrapping of call-in types doesn't cause weird indenting.
Fixed #235
=> Reformat callin modal

client/chat.coffee, lib/model.coffee, server/server.coffee
Allows the chat panel to show only the contiguous messages, instead of anything in the Messages collection that might be there because of other subscriptions.
Fixes #383
=> Add 'from_chat_subscription' marker to messages from recent-messages subscription

package-lock.json, package.json
Since we use the github action we shouldn't need this.
=> Remove direct dependency on coveralls npm package

blackboard.html
Spreadsheet, doc, and jitsi call links open in a different window; the puzzle link should also.
=> Open hunt site link in new window

client/blackboard.coffee
Stopping it for everything under the dropdown meant the X in the clear button was inactive.
Fixes #494
=> Only stop propagation at the level of the filter dropdown menu

server/imports/drive_change_polling.coffee, server/imports/drive_change_polling.test.coffee
Instead of faking setTimeout and clearTimeout, which tends to break Meteor as it uses them in the background, pass the object containing them to the constructor.
Fixes #493
=> Fix flaky test for Drive change polling

.meteor/packages, .meteor/versions, client/imports/map.coffee, client/imports/map.test.coffee, client/imports/objectColor.coffee, client/imports/objectColor.test.coffee
Use md5 for generating psuedorandom colors and jittering map positions, since we don't need security.
=> Remove sha package

blackboard.html, blackboard.less, client/blackboard.coffee
By hiding solved puzzles in solved metas (replaced by a solved/total count) and using flex instead of a table, the entire hunt is visible in a much smaller height.
Fixes #528
=> Condensed status grid

blackboard.html, client/blackboard.app-test.coffee, client/blackboard.coffee
Since some things can appear multiple times (metas that feed metametas, leaves that feed multiple metas, or favorite/stuck puzzles), when you click something to edit it, focus the copy you clicked, not the first one on the page.
Fixes #548
=> Edit the version of something you clicked

client/header.coffee
Don't pass something nullish to canonical when you're already logged in and skipping the login page.
Fixes #547
=> No spurious exception on startup

client/blackboard.coffee, client/header.coffee, client/imports/modal.coffee, client/main.coffee, client/puzzle.coffee, header.html, modal.html, page.html
Instead of having a global confirm dialog that's always in the page, add it to the dom when it's required and remove it when it's finished.
=> Standalone confirm dialog

server/hubot-scripts/metas.test.coffee
If you only wait for the effect, the database can be cleared before the response is given, which means the response can be seen by the next test case.
Fixes #579
=> Always wait for message in metas hubot test

blackboard.html, blackboard.less, callins.html, client/blackboard.app-test.coffee, client/blackboard.coffee, client/imports/ok_cancel_events.coffee, client/imports/ui/components/edit_field/edit_field.coffee, client/imports/ui/components/edit_field/edit_field.html, client/imports/ui/components/edit_object_title/edit_object_title.coffee, client/imports/ui/components/edit_object_title/edit_object_title.html, client/imports/ui/components/edit_object_title/edit_object_title.less, client/imports/ui/components/edit_tag_name/edit_tag_name.coffee, client/imports/ui/components/edit_tag_name/edit_tag_name.html, client/imports/ui/components/edit_tag_name/edit_tag_name.less, client/imports/ui/components/edit_tag_value/edit_tag_value.coffee, client/imports/ui/components/edit_tag_value/edit_tag_value.html, client/imports/ui/components/edit_tag_value/edit_tag_value.less, client/puzzle.coffee, lib/model.coffee, puzzle.html
Instead of the data-bbedit attribute and a handler on the blackboard template, make small templates that can each edit one kind of thing. Adds them to the puzzle info panel.
Fixes #567, Fixes #568
=> Editable components

lib/model.coffee, server/imports/drive.coffee, server/imports/drive.test.coffee, server/imports/drive_change_polling.coffee, server/imports/drive_change_polling.test.coffee, server/methods/newPuzzle.test.coffee, server/methods/renamePuzzle.test.coffee
Don't create a text document for every puzzle because we don't always need it, but embed it when we manually create one.
Fixes #574
=> On-demand document embedding

blackboard.less, client/puzzle.app-test.coffee, client/puzzle.coffee, puzzle.html
A toggle button to show all unattached puzzles, and for metametas, one to show all grandfeeders. When either is toggled, all shown puzzles have a checkbox to control whether it feeds the current meta or not.
=> Allow feeding and unfeeding puzzles from the puzzle info pane of metas

client/imports/jitsi.js
Don't show a webpage that says to use the app. Fixes #774
=> Use web jitsi interface on mobile

client/callins.js, client/imports/ui/pages/logistics/logistics.js, server/server.js
Remove them from the "callins" publish (now called "pending-callins"). The callin row now subscribes to all callins for the puzzle in question. Fixes #811
=> Don't subscribe to all rejected callins

client/imports/router.js, client/imports/ui/pages/statistics/statistics_chart.js
`start_time` and `end_time` query parameters allow viewing a specific time range, e.g. for a post-hunt report.
=> Allow truncating statistics

client/imports/ui/pages/logistics/logistics.js
If you dragged over the dropdown but didn't drop there, the dropdown("toggle") would install a listener that would interfere with the click handlers, so you couldn't make a new puzzle by clicking anymore. This didn't happen if you made it to e.g. the round button without ever dragging over the dropdowns. Fixes #934
=> Fix toggling meta/standalone dropdowns on dragout

client/imports/serviceworker.js
window.navigator doesn't have a serviceWorker member in Firefox private browsing mode, so don't crash on startup.
=> Support Firefox private browsing mode

client/blackboard.js, client/imports/presence_index.js, client/imports/ui/pages/logistics/logistics.js
If you leave and rejoin a room at just the right time, the added and removed messages can get delivered out of order, which meant you were added to a room you were already in, then removed. Now we keep a count of the times you're in the room. Fixes #930
=> Fix race condition on presence index

package.json
Meteor doesn't run on node >14 yet, so set that in package.json to hint dependabot not to update to packages that don't work on 14.
=> Set engineStrict

client/imports/ui/components/edit_field/edit_field.js, client/imports/ui/components/edit_tag_value/edit_tag_value.js
If a field or tag contains a URL-like thing which we have converted to a link, clicking the link shouldn't edit the field/tag.
=> Stop propagation at a in editable values

client/blackboard.html, client/blackboard.js, client/blackboard.less
Also close dropdown on enter, and allow clearing search without reopening dropdown.
Fixes #1316
=> Show query in user search header

client/blackboard.html, client/blackboard.less, client/imports/settings.js, client/imports/settings.test.js, client/options_dropdown.html, client/options_dropdown.js, client/options_dropdown.less
* Rename "Visible Columns" submenu to "Column Options".
* Add Name as a disabled setting in "Column Options" since you can't hide it.
* Rename "Compact Mode" to "Hide Tags" and nest under "Name"
* Add "Added" column, hidden by default.
* Add display style option for "Who's Working"
Fixes #1327
=> Column options refinements

client/mechanics.js
The .includes check doesn't work without strict mode because the helper
function gets called with .apply, so that `this` is a String object
rather than a primitive string.
(Maybe strict mode should just be enabled everywhere? Looks like it was
lost during decaffeination in #752.)
=> Fix favorite mechanic check with strict mode

client/chat.app-test.js, client/chat.js
if you type `#puzzles/foo` match puzzles with foo in their name. Previously that would only match puzzles with foo in their id, but #foo would match anything with foo in its name.
Fixes #1387
=> Autocomplete room name after room type

client/chat.less
so the hover controls are positioned relative to them.
=> Make action and system messages relative

client/imports/notification.js
Seems like this doesn't happen on localhost, but on a remote host Notification.permission can be "default" on startup, then change to "granted". That makes us think we have to ask, so the button says "enable" but clicking it works instantly because they're already enabled.
Intended to fix #1395
=> Detect permission change

client/chat.js, client/geolocation.js
Since chat messages and users are separate subscriptions, there's no guaranteeing the users load first, which could mean botuser() initially returns null, so check its value to prevent exceptions on page load.
=> Always check the return value of botuser()

lib/imports/collections.js
{to, room_name, timestamp} and {nick, room_name, timestamp} were added with the expectection that the room subscription would use them, but Mongodb prefers to use the use the {room_name, timestamp} index and filter out the few private messages, which makes sense because they're rare.
{timestamp} was only used by the Hubot observer, but I changed that to use Mongo's native change stream (to not keep the messages in memory) so it's no longer used.
{mention{ should always have had a partial filter expression since we never want to search for messages that don't mention anybody.
Fixes #1435
=> Clean up some indices on the Message collection

client/chat.less
Should make its trailing space behavior more consistent with other browsers, e.g. not stripping them out randomly.
Fixes #1583
=> Use white-space: -moz-pre-space in chat input
